include: package:lint/analysis_options_package.yaml

linter:
  rules:
    # ------ Disable individual rules ----- #
    #                 ---                   #
    # Turn off what you don't like.         #
    # ------------------------------------- #

    # Use parameter order as in json response
    always_put_required_named_parameters_first: false

    # Util classes are awesome!
    avoid_classes_with_only_static_members: false

    # ------ Enable individual rules ------ #
    #                 ---                   #
    # These rules here are good but too     #
    # opinionated to enable them by default #
    # ------------------------------------- #
    
    # Make constructors the first thing in every class
    sort_constructors_first: true
    
    prefer_single_quotes: true

    # Back to the 80s
    lines_longer_than_80_chars: true

    import_of_legacy_library_into_null_safe: true

analyzer:

