name: geekhub_api
description: 基于网页爬虫的 GeekHub API。

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  dio: ^3.0.10
  dio_cookie_manager: ^1.0.0
  freezed_annotation: ^0.12.0
  html: ^0.14.0+4
  html2md: ^0.5.1
  logging: ^0.11.4

dev_dependencies:
  build_runner: ^1.10.11
  freezed: ^0.12.6
  lint: ^1.5.1
  mockito: ^4.1.3
  test: ^1.14.4
  test_coverage: ^0.5.0
